//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Xml.Serialization;

    [DebuggerDisplay("{" + nameof(GetDebuggerDisplay) + "(),nq}")]
    public partial class post
    {
        List<Link> links = new List<Link>();
        public int id { get; set; }
        public string status { get; set; }
        public List<Link> Links
        {
            get{return links;}
            
        }
        private string GetDebuggerDisplay()
        {
            return ToString();
        }
    }
}
